version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    container_name: client
    tty: true
  api:
    build: ./api
    ports:
      - '3001:3001'
    container_name: api
